title: My clever blog title
author: Dillon
email: dlstadther+github@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome site description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
